### ISSUE TITLE
fysom.FysomError: event inappropriate because previous transition did not complete

### ISSUE THREAD

**Issue by raj2569** [mriehl/fysom#20]
Hi,
```
Traceback (most recent call last):
  File "log.py", line 220, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 216, in fn
    "event %s inappropriate because previous transition did not complete" % event)
fysom.FysomError: event myevent inappropriate because previous transition did not complete
```

I get this error occasionally in my program. I understand that this happens because one event was received when another event was being processed. But what strategy can be used to make sure that the event is not missed even when previous transition is going on? Some sort of queuing mechanism is possible?

**Comment by mriehl** [comment]
Hi,

You're right, it looks like you have an async transition that did not complete (`transition()` not called) and then you get a new event, which is illegal as of now.
I think queueing would tremendously increase complexity (who gets the error if the queued event is invalid? How do you know if it's valid when you queue it?).

I think you should try to find out if the event you're handling needs to be handled asynchronously. Maybe you can break up this async model by adding more states?

For example let's say your async transition is about curling an URL within a thread.
Right now you have the event `request` (which does not complete the transition until you call `transition()` on the FSM, after the thread terminates). The question you need to ask is, what will you do if `myevent` shows up and the thread is still alive? What if the thread terminated? Does it make a difference?

This could be mapped to new states : introduce the states `curl-started` and `curl-finished`, and corresponding events.
You can now accept `myevent` in `curl-started` and `curl-finished` - and handle it differently (or not).
Am I making sense?

**Comment by raj2569** [comment]
Hi,

It is not an async program. The code checks some GPIO pins in a while loop and make appropriate state transitions based on the value of the GPIO pins. The simplified code is as follows:

```
def timer_callback():
    fsm.timer_fired()

    while True:
    if GPIO.input(pin1):
        fsm.got_high()
        time.sleep(0.05)
    else:
            threading.Timer(60, timer_callback).start()
            fsm.got_low()

    if GPIO.input(pin2):
        fsm.myevent1()
    else:
        fsm.myevent()
```

In the above code, I think the async event transition happens in the `timer_callback` thread. In my case the `timer_callback` thread can wait if any event is in progress and do the state transition only after any in-progress event is complete. But how can I implement this check?

**Comment by mriehl** [comment]
Thanks for clearing that up. So your problem is essentially that event handling is not atomic and some thread might trigger an event while a transition is in progress.

The solution is probably wrapping the state machine so that transitions are atomic - I'm not sure about the best way to go about this.
There is no way to make it generic enough so that it works out of the box in every case - you might need a filelock, a posix semaphore or w/e.. There's also the issue of coarseness - would the transitions need to be atomic or are callbacks also a part of the critical section?

The simplest way to do this as I see it would be to accept some kind of pre-transition and post-transition callback when creating the FSM. These callbacks would be run before /after each transition, allowing you to lock/unlock with a lockfile for example.
This would serialize event triggers. 

What do you think? Did you have something else in mind? What about including callbacks in the critical section.

**Comment by mriehl** [comment]
To expand on my last comment, there are basically two possibilities:

* You implement a custom fix for your use case
This can be achieved with inheritance, for example (note that this version would run the callbacks within the locked critical section)

```python
class ThreadSafeFysom(Fysom):

    def __init__(self, *args, **kwargs):
        Fysom.__init__(self, *args, **kwargs)

    def _build_event(self, event):
        base_event = Fysom._build_event(self, event)
        def threadsafe_event(*args, **kwargs):
            print("Acquiring lock") # replace this with actual locking
            base_event(*args, **kwargs)
            print("Releasing lock!") # replace this with actual locking

        return threadsafe_event
```

* We try to find a generic solution that fits in the fysom library itself, making your job easier.

**Comment by raj2569** [comment]
I took another approach.

Instead of calling the state transition from the  thread, I set a boolean variable in the thread, and that is checked in the main loop. If the boolean variable is set, I will do the state transition in the main loop itself. This will remove the asyncness of the state transition and the whole thing will become serial.

Did some testing here and it seems to work. 

Thanks a lot for your assistance and ideas, It really helped!

**Comment by mriehl** [comment]
Hi, thanks for getting back to me. Sounds like the most simple solution (if it works with the FSM model you have).
I'm going to close this for now, but renaming to "Event transition thread safety" so that we can continue the discussion here if someone requests thread safety.
Feel free to reopen as adequate!
